---
- name: "Create temp directory for Cert Location"
  ansible.builtin.command: mkdir -p /tmp/k3s/certs

- name: "Create Sealed-Secrets namespace: sealed-secrets"
  ansible.builtin.command: sudo kubectl create namespace sealed-secrets
  ignore_errors: yes

- name: "Generate a new RSA key pair(certificate) for Sealed Secrets"
  ansible.builtin.command: openssl req -x509 -days {{sealed_secrets_cert_days_valid}} -nodes -newkey rsa:{{sealed_secrets_key_size}} -keyout "/tmp/k3s/certs/{{sealed_secrets_private_key}}" -out "/tmp/k3s/certs/{{sealed_secrets_public_key}}" -subj "/CN=sealed-secret/O=sealed-secret"

- name: "Delete existing secret if it exists"
  ansible.builtin.command: kubectl -n "{{sealed_secrets_namespace}}" delete secret "{{sealed_secrets_secret_name}}"
  ignore_errors: yes

- name: "Create a tls k8s secret, using your recently created RSA key pair"
  ansible.builtin.command: kubectl -n "{{sealed_secrets_namespace}}" create secret tls "{{sealed_secrets_secret_name}}" --cert="/tmp/k3s/certs/{{sealed_secrets_public_key}}" --key="/tmp/k3s/certs/{{sealed_secrets_private_key}}"

- name: "Copy files from remote host to local machine"
  ansible.builtin.fetch:
    src: "/tmp/k3s/certs/{{ item }}"
    dest: "./sealed-secrets-key/remote/{{ item }}"
    flat: yes
  with_items:
    - "{{ sealed_secrets_private_key }}"
    - "{{ sealed_secrets_public_key }}"

- name: "Delete keys from remote host"
  ansible.builtin.file:
    path: "/tmp/k3s/certs/{{ item }}"
    state: absent
  with_items:
    - "{{ sealed_secrets_private_key }}"
    - "{{ sealed_secrets_public_key }}"
