---
- name: "Create temp directory for Cert Location"
  ansible.builtin.command: mkdir -p /tmp/k3s/certs

- name: "Create Sealed-Secrets namespace: sealed-secrets"
  ansible.builtin.command: sudo kubectl create namespace sealed-secrets
  ignore_errors: yes

- name: "Copy private key from local machine to remote host"
  ansible.builtin.copy:
    src: "{{ sealed_secrets_private_key_path }}"
    dest: "/tmp/k3s/certs/{{ sealed_secrets_private_key }}"
    mode: '0600'

- name: "Copy public key from local machine to remote host"
  ansible.builtin.copy:
    src: "{{ sealed_secrets_public_key_path }}"
    dest: "/tmp/k3s/certs/{{ sealed_secrets_public_key }}"
    mode: '0600'

- name: "Delete existing secret if it exists"
  ansible.builtin.command: kubectl -n "{{sealed_secrets_namespace}}" delete secret "{{sealed_secrets_secret_name}}"
  ignore_errors: yes

- name: "Create a tls k8s secret, using your recently created RSA key pair"
  ansible.builtin.command: kubectl -n "{{sealed_secrets_namespace}}" create secret tls "{{sealed_secrets_secret_name}}" --cert="/tmp/k3s/certs/{{sealed_secrets_public_key}}" --key="/tmp/k3s/certs/{{sealed_secrets_private_key}}"

- name: "Delete keys from remote host"
  ansible.builtin.file:
    path: "/tmp/k3s/certs/{{ item }}"
    state: absent
  with_items:
    - "{{ sealed_secrets_private_key }}"
    - "{{ sealed_secrets_public_key }}"
